
buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Put all build outputs under <projectRoot>/build so Flutter can find the APK
rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// Flutter expects this to ensure :app is evaluated early
subprojects {
    project.evaluationDependsOn(':app')
}

// Clean task used by `flutter clean`
tasks.register("clean", Delete) {
    delete rootProject.buildDir
}